import * as sorted from "./sorted";
import { zip, chunkArray } from "./zip";
import { removeDuplicates, noDuplicates, walkBackString, findAllCommonPrefixes } from "./remove.duplicates";
declare const _default: {
    chunkArray: typeof chunkArray;
    noDuplicates: typeof noDuplicates;
    walkBackString: typeof walkBackString;
    findAllCommonPrefixes: typeof findAllCommonPrefixes;
    removeDuplicates: typeof removeDuplicates;
    zip: typeof zip;
    BisectArray: typeof sorted.BisectArray;
    ReverseSortedArray: typeof sorted.ReverseSortedArray;
    SortedArray: typeof sorted.SortedArray;
    ReverseNumberArray: typeof sorted.ReverseNumberArray;
    SortedNumberArray: typeof sorted.SortedNumberArray;
    ReverseStringArray: typeof sorted.ReverseStringArray;
    SortedStringArray: typeof sorted.SortedStringArray;
    ReverseCompareArray: typeof sorted.ReverseCompareArray;
    SortedCompareArray: typeof sorted.SortedCompareArray;
};
export default _default;
